### ISSUE TITLE
Github: Highlighting makes text dissapear

### ISSUE THREAD

**Issue by fpigeon** [gerane/VSCodeThemes#27]
# Disappearing when Highlighting

When I select text like in the screenshot the selected text disappears. Thanks for adding all these great Color themes to **VSCode**. 

<img width="802" alt="screen shot 2017-02-06 at 10 41 20 pm" src="https://cloud.githubusercontent.com/assets/4629398/22678169/b5f70592-ecbd-11e6-9f77-58ea857162fb.png">
<img width="788" alt="screen shot 2017-02-06 at 10 41 37 pm" src="https://cloud.githubusercontent.com/assets/4629398/22678170/b7e71da6-ecbd-11e6-9501-2e94e02f7e53.png">

**Comment by gerane** [comment]
Which theme is this?

**Comment by fpigeon** [comment]
This is the Github theme. Thanks for taking a look.

**Comment by gerane** [comment]
I will try to take a look at it this weekend.

**Comment by fpigeon** [comment]
thanks @gerane. I appreciate you helping the vscode community with all these great themes.

**Comment by gerane** [comment]
@fpigeon I tested changing the selection color to a lighter shade of #72d3d1

Do you think this works better? The comments are a little hard to see, but given they are comments I wasn't sure if they really needed to be changed. Here is a quick example.

![capture](https://cloud.githubusercontent.com/assets/6662208/23106272/5c202e84-f6b0-11e6-8d13-99d733cfccdb.PNG)

What sort of highlighting would you think would work best? I was hesitant to try a lighter gray tinted color since that would likely be even harder to avoid conflicts.

**Comment by fpigeon** [comment]
@gerane This highlight color looks great and I think is consistent with the theme, Agree that grey would not work as well. Looking forward to the update as this is my fav light theme.

**Comment by MarcelloTheArcane** [comment]
This happens with the Earthsong theme (#54) - I've changed my colour to `#995c40`.

What do you think?

**Before**:
![before](https://user-images.githubusercontent.com/21159570/70794404-7f390f80-1d95-11ea-86ef-747f7a414d71.png)
**After**:
![after](https://user-images.githubusercontent.com/21159570/70795533-ec4da480-1d97-11ea-9d4d-090c4861cc66.png)
